name: .NET

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Print current dir
        run: pwd

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Print current dir
        run: pwd

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore

      - name: Print current dir
        run: pwd

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: ./
          key: ${{ runner.os }}-${{ hashFiles('**/*.dll') }}

      - name: Print current dir
        run: pwd

      - name: Build
        run: dotnet build --configuration Release --no-restore
  
  test:
    name: Test
    
    needs: build

    runs-on: ubuntu-latest
    
    steps:
      - name: Print current dir
        run: pwd

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Print current dir
        run: pwd

      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: ./
          key: ${{ runner.os }}-${{ hashFiles('**/*.dll') }}

      - name: Print current dir
        run: pwd

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal